M48
; DRILL file {KiCad 7.0.8-7.0.8~ubuntu23.04.1} date sø. 19. nov. 2023 kl. 22.38 +0100
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2023-11-19T22:38:14+01:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,7.0.8-7.0.8~ubuntu23.04.1
; #@! TF.FileFunction,NonPlated,1,4,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.1693
%
G90
G05
T1
X4.4Y-1.9
X4.4Y-5.425
X7.175Y-1.9
X7.175Y-5.425
T0
M30
