M48
; DRILL file {KiCad 7.0.9-7.0.9~ubuntu23.04.1} date ti. 02. jan. 2024 kl. 14.37 +0100
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2024-01-02T14:37:17+01:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,7.0.9-7.0.9~ubuntu23.04.1
; #@! TF.FileFunction,NonPlated,1,4,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.1693
%
G90
G05
T1
X1.5Y-1.865
X1.5Y-5.39
X4.275Y-1.865
X4.275Y-5.39
T0
M30
